# Generated by Django 5.1.3 on 2024-12-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('date_of_birth', models.DateField(default=0)),
                ('fathers_name', models.CharField(default=0, max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('customerid', models.IntegerField(default=0, primary_key='customerid', serialize=False)),
                ('accountdetails', models.CharField(default=0, max_length=70)),
            ],
        ),
    ]
